### ISSUE TITLE
zip file not available to download

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#174] opened 2024-11-21 17:22 UTC
**Describe the bug**

Zip file download for Working or Clean dataset are not working for this particular WQP dataset.

**To Reproduce**

1. Query WQP for data using the following filters:

- startDate = "2019-04-15",
- endDate = "2023-04-15",
- sampleMedia = c("Water", "water"),
- siteType = c("Stream", "Lake, Reservoir, Impoundment"),
- statecode = "WY"

This may take a few minutes to run.

2. Try to download the Working Dataset from the overview tab. 

The zip file is not available. This is strange because it is the only dataset I've run into this particular issue with. You can still run through other features/tabs in the app, but the download does not work. It tries to download the data as a HTML Document (*.htm).

**Expected behavior**

Use should be able to download a .zip file.

**Screenshots**

![image](https://github.com/user-attachments/assets/03126351-5cfe-4c39-8ef0-3d9e7f085f47)

<img width="491" alt="image" src="https://github.com/user-attachments/assets/b462e2b3-5e19-424d-b103-98ba8e882021">

**Reminders for TADA contributors addressing this issue**

Bug fixes should include the following work:

-   [ ] Create or edit the code.

-   [ ] Document all code using line/inline and/or multi-line/block comments
    to describe what is does.

-   [ ] Create or edit tests in tests/testthat folder to help prevent and/or 
    troubleshoot potential future issues.

-   [ ] If your code edits impact other functionality in the shiny 
    app, ensure those are updated as well.

-   [ ] Run styler::style_pkg(), devtools::document(), and devtools::check() 
    and address any new notes or issues before creating a pull request.

**Comment by JamesBisese** [comment] 2024-11-25 15:18
I am seeing the same problem for all 'Save Working' and 'Save Final' datasets.  I am going to download a new copy of both sides from the repo and see it the problem is in there.  It is a recent issue, since last week I was not having a problem downloading files.  Now I get the '.htm' download issue reported by Christina

**Comment by JamesBisese** [comment] 2024-11-25 16:07
Using a fresh version of TADAShiny and EPATADA, the download is failing.  There is this error
`````
Warning: Error in data.frame: arguments imply differing number of rows: 12, 13
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
`````

**Comment by JamesBisese** [comment] 2024-12-02 21:06
The error is related to the 2 site types selected.  If you run any query and use both 'Stream' and 'Lake, Reservoir, Impoundment' you get the same error condition.  Even if there is no data matching one of the two site types.

**Comment by triphook** [comment] 2024-12-04 16:56
Resolved in branch zip_fix

**Closed as completed by triphook** 2024-12-04 16:56 UTC
